config/routes.rb
Moika::Application.routes.draw do

  get "normal_users/show"
  root 'map#show'
  get "map/show"

  get "sp/:id", to: "static_pages#show", as: "static_page"
  get "banners/update"

  get "user/:id", to: "users#show", as: '/user'
  get "users/registration", to: "users#registration", as: 'registration'
  get "users/login", to: "users#login", as: 'login'

  get "normal_user/:id", to: "normal_users#show", as: '/normal_user'

  devise_for :users, controllers: { registrations: "registrations" }
  devise_for :normal_users, controllers: { registrations: "registrations" }

  resources :car_washes do
    get :update_map, on: :collection
    resources :comments, only: [:index, :create]
    resources :requests
    resources :messages, only: [:index, :show, :update]
    resources :normal_user_messages
    resources :banners, only: [:index, :update]
    resources :payments, only: [:index]
    resources :invoices, only: [:new, :create, :show]
    delete 'delete_file/:id', to: 'banners#delete_file', as: '/delete_file'
  end

  put 'car_washes/:id/update_main_action', to: 'car_washes#update_main_action', as: '/car_washes_update_main_action'
  post 'car_washes/:id/subscribe/:user_id', to: 'car_washes#subscribe', as: '/car_washes_subscribe'

  controller :robokassa do
    get "robokassa/:notification_key/notify"   => :notify,  :as => :robokassa_notification

    get "robokassa/success"  => :success, :as => :robokassa_on_success
    get "robokassa/fail"     => :fail,    :as => :robokassa_on_fail
  end

  namespace :admin do
    get '', to: 'dashboard#main', as: '/'
    get 'load_data_from_ya', to: 'dashboard#load_data_from_ya', as: '/load_data_from_ya'
    resources :users
    resources :messages, only: [:index, :show, :create, :destroy]
    resources :banners
    resources :static_pages
    resources :car_washes
    get 'add_car_wash/:id', to: 'users#add_car_wash', as: '/add_car_wash'
    delete 'delete_file/:id', to: 'banners#delete_file', as: '/delete_file'
  end
  match "*path" => redirect("/"), via: :all
end

app/models/normal_user.rb
class NormalUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :subscribes
  has_many :car_washes, through: :subscribes

  has_many :sent_messages, class_name: "NormalUserMessage", foreign_key: "sender_id"
  has_many :received_messages, class_name: "NormalUserMessage", foreign_key: "receiver_id"

end

class NormalUser::ParameterSanitizer < Devise::ParameterSanitizer
  def sign_up
    default_params.permit(:email, :name, :phone, :password, :password_confirmation)
  end
end

app/controllers/normal_users_controller.rb
class NormalUsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
    @car_washes = @normal_user.car_washes
  end


  private
    def set_user
      @normal_user = NormalUser.find(params[:id])
    end
end

app/helpers/normal_users_helper.rb
module NormalUsersHelper
end

app/views/normal_users/show.html.haml
#car_washes_user_list
  .base-grey-panel 
    %h4.text-center Выбранные Вами Автомойки
  %ul
    - unless @car_washes.blank?
      - @car_washes.each do |cw|
        .steel_button
          %li{id: "car_wash_#{cw.id}"}
            = link_to(car_wash_normal_user_messages_path(cw)) do
              =cw.title
              (
              %span#normal_user_messages_count=cw.normal_user_messages.where(receiver_id: @normal_user.id).count
              )
.right-8
  - if @car_washes.blank?
    .base-grey-panel
      - t('.normal_user_registration_message').each {|x| haml_tag :h4, x, class: "text-center" }
  - else
    %ul.user_car_washes
      - @car_washes.each do |cw|
        = subscribe_to "/normal_users_messages/#{cw.id}/#{current_normal_user.id}"
        %li.base-grey-panel
          .red= cw.title
          %ul.user_actions
            = cw.actions.find_each do |action|
              %li= action.text