config/routes.rb
Moika::Application.routes.draw do

  get "normal_users/show"
  root 'map#show'
  get "map/show"

  get "sp/:id", to: "static_pages#show", as: "static_page"
  get "banners/update"

  get "user/:id", to: "users#show", as: '/user'
  get "users/registration", to: "users#registration", as: 'registration'
  get "users/login", to: "users#login", as: 'login'

  get "normal_user/:id", to: "normal_users#show", as: '/normal_user'

  devise_for :users, controllers: { registrations: "registrations" }
  devise_for :normal_users, controllers: { registrations: "registrations" }

  resources :car_washes do
    get :update_map, on: :collection
    resources :comments, only: [:index, :create]
    resources :requests
    resources :messages, only: [:index, :show, :update]
    resources :normal_user_messages
    resources :banners, only: [:index, :update]
    resources :payments, only: [:index]
    resources :invoices, only: [:new, :create, :show]
    delete 'delete_file/:id', to: 'banners#delete_file', as: '/delete_file'
  end

  put 'car_washes/:id/update_main_action', to: 'car_washes#update_main_action', as: '/car_washes_update_main_action'
  post 'car_washes/:id/subscribe/:user_id', to: 'car_washes#subscribe', as: '/car_washes_subscribe'

  controller :robokassa do
    get "robokassa/:notification_key/notify"   => :notify,  :as => :robokassa_notification

    get "robokassa/success"  => :success, :as => :robokassa_on_success
    get "robokassa/fail"     => :fail,    :as => :robokassa_on_fail
  end

  namespace :admin do
    get '', to: 'dashboard#main', as: '/'
    get 'load_data_from_ya', to: 'dashboard#load_data_from_ya', as: '/load_data_from_ya'
    resources :users
    resources :messages, only: [:index, :show, :create, :destroy]
    resources :banners
    resources :static_pages
    resources :car_washes
    get 'add_car_wash/:id', to: 'users#add_car_wash', as: '/add_car_wash'
    delete 'delete_file/:id', to: 'banners#delete_file', as: '/delete_file'
  end
  match "*path" => redirect("/"), via: :all
end

app/models/car_wash.rb
class CarWash < ActiveRecord::Base
  default_scope {order('id DESC').order('rating DESC')}
  after_create :create_empty_banners
  after_create :create_payment
  after_validation :geocode
  after_update :update_signals, if: :signal_changed?
  before_save :update_signal_type

  has_many :users
  has_many :actions
  has_many :comments
  has_many :requests
  has_many :messages
  has_many :normal_user_messages
  has_many :banners
  has_many :payments
  has_many :invoices
  has_many :subscribes
  has_many :normal_users, through: :subscribes

  accepts_nested_attributes_for :actions
  geocoded_by :address, :latitude  => :lat, :longitude => :lon
  

  def activate!
    self.update(activated: true)
  end

  def unread_requests_count
    self.requests.unread.count
  end

  def unread_messages_count
    self.messages.unread.count
  end
 
  def signal_human
    self.signal ? I18n.t('signal_open'):I18n.t('signal_close')
    
  end
  def update_signals
    logger.debug "vatagin_from update signal_changed:#{self.title}:#{self.signal_changed}"
  end

  def main_action
     actions.includes(:action_type).where("action_types.text" => "main").first
  end

  def main_action_text
    main_action.try(:action_text).try(:text)
  end

  def actions_by_type(type)
     actions.includes(:action_type).where("action_types.text" => type.to_s)
  end

  def actiontext_by_type(type)
    actions_by_type(type).try(:action_text).first.try(:text)
  end

  def enable_blink
    self.blink = true
    self.save!
  end

  def disable_blink
    self.blink = false
    self.save!
  end

  def update_signal_type
    signal_type = self.signal_type
    logger.debug "vatagin: #{signal_type}"
    case signal_type
    when /blink/
      logger.debug "vatagin: #{self.blink}"
      logger.debug "vatagin: #{self.videoned}"
      logger.debug "vatagin: #{self.action_on_map}"
      self.blink = true
      self.videoned = false
      self.action_on_map = false
      logger.debug "vatagin: #{self.blink}"
      logger.debug "vatagin: #{self.videoned}"
      logger.debug "vatagin: #{self.action_on_map}"
    when /action_on_map/
      logger.debug "vatagin: #{self.blink}"
      logger.debug "vatagin: #{self.videoned}"
      logger.debug "vatagin: #{self.action_on_map}"
      self.blink = false
      self.videoned = false
      self.action_on_map = true
      logger.debug "vatagin: #{self.blink}"
      logger.debug "vatagin: #{self.videoned}"
      logger.debug "vatagin: #{self.action_on_map}"
    when /videoned/
      logger.debug "vatagin: #{self.blink}"
      logger.debug "vatagin: #{self.videoned}"
      logger.debug "vatagin: #{self.action_on_map}"
      self.blink = false
      self.videoned = true
      self.action_on_map = false
      logger.debug "vatagin: #{self.blink}"
      logger.debug "vatagin: #{self.videoned}"
      logger.debug "vatagin: #{self.action_on_map}"
    else
      logger.debug "vatagin: #{self.blink}"
      logger.debug "vatagin: #{self.videoned}"
      logger.debug "vatagin: #{self.action_on_map}"
      self.blink = false
      self.videoned = false
      self.action_on_map = false
      logger.debug "vatagin: #{self.blink}"
      logger.debug "vatagin: #{self.videoned}"
      logger.debug "vatagin: #{self.action_on_map}"
    end
  end

  protected
    def create_empty_banners
      banners_data = [
        {place: "client_fat_top"},
        {place: "client_thin_bottom"},
        {place: "client_thin_top_1"},
        {place: "client_thin_top_2"},
        {place: "client_thin_top_3"},
        {place: "client_thin_top_4"}
      ]

      banners_data.each do |data| 
        self.banners << ClientBanner.new(data)
      end
      self.banners << ClientVideoBanner.new
    end
    def create_payment
      self.payments << Payment.new(amount: 6000.00)
    end

  private
    def lat_and_lon_nil?
      self.lat.nil? && self.lon.nil?
    end
end

app/controllers/admin/car_washes_controller.rb
class Admin::CarWashesController < AdminController
  before_action :set_car_wash, only: [:show, :edit, :update, :destroy]
  def index
    @car_washes = CarWash.all
  end

  def show
  end

  def new
    @car_wash = CarWash.new
  end

  def edit
  end

  def create
    @car_wash = CarWash.new(car_wash_params)

    respond_to do |format|
      if @car_wash.save
        format.html { redirect_to [:admin, @car_wash], notice: 'Car wash was successfully created.' }
        format.json { render action: 'show', status: :created, location: @car_wash }
      else
        format.html { render action: 'new' }
        format.json { render json: @car_wash.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @car_wash.update(car_wash_params)
        format.html { redirect_to [:admin, @car_wash], notice: 'Car wash was successfully updated.' }
        format.json { render action: 'show', status: :created, location: @car_wash }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car_wash.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private

    def set_car_wash
      @car_wash = CarWash.find(params[:id])
    end

    def car_wash_params
      params.require(:car_wash).permit(:title,
                                       :address,
                                       :lat, :lon,
                                       :contacts,
                                       :site_url,
                                       :video_url1, :video_url2,
                                       :vk_url, :odn_url,
                                       :blink, :videoned,
                                       :signal_type)
    end
end

app/controllers/car_washes_controller.rb
class CarWashesController < ApplicationController
  before_action :set_car_wash, only: [:show, :edit, :update, :update_main_action, :destroy]
  before_action :set_actions, only: [:show, :edit]
  before_filter :check_access, :only => [:new, :edit, :update, :destroy]

  # GET /car_washes
  # GET /car_washes.json
  def index
    @car_washes = CarWash.all
  end

  def update_map
    @car_washes = CarWash.where('updated_at > ?', params[:updated_at])
    @updated_at = Time.now.utc
  end

  # GET /car_washes/1
  # GET /car_washes/1.json
  def show
    if @car_wash.nil?
      redirect_to :index
    end
    @left_actions = @car_wash.actions_by_type(:left)
    @bottom1_actions = @car_wash.actions_by_type(:bottom1)
    @bottom2_actions = @car_wash.actions_by_type(:bottom2)
    @vacancy_actions = @car_wash.actions_by_type(:vacancy)
    @unread_requests_count = @car_wash.requests.unread.count
    @banners = @car_wash.banners
  end

  def new
    @car_wash = CarWash.new
  end

  # GET /car_washes/1/edit
  def edit
    @full = (params['full'] == '1')
    @payment = Payment.new(car_wash_id: @car_wash.id, amount: 6000.00)
  end

  # POST /car_washes
  # POST /car_washes.json
  def create
    @car_wash = CarWash.new(car_wash_params)

    respond_to do |format|
      if @car_wash.save
        format.html { redirect_to @car_wash, notice: 'Car wash was successfully created.' }
        format.json { render action: 'show', status: :created, location: @car_wash }
      else
        format.html { render action: 'new' }
        format.json { render json: @car_wash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_washes/1
  # PATCH/PUT /car_washes/1.json
  def update
    params_actions = params[:car_wash][:actions]
    
    unless params_actions.blank?
      params_actions.each do |params_action|
        action = @car_wash.actions_by_type(params_action[:action_type_text]).first
        if action.nil?
         @car_wash.actions.build(
           action_text: ActionText.create(text: params_action[:text]), 
           action_type: ActionType.find_by(text: params_action[:action_type_text]))
        else
         action.action_text.update(text: params_action[:text])
        end
      end
    end

    respond_to do |format|
      if @car_wash.update(car_wash_params)
        format.html { redirect_to @car_wash, notice: 'Car wash was successfully updated.' }
        format.json { head :no_content }
        format.js { 
          if params_actions.blank?
            render "signal_update"
          else
            case params_actions.first[:action_type_text]
            when "main"
              render 'main_action_update'
            when "left"
              render 'left_action_update'
            end
          end
        }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car_wash.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_actions
  end

  def update_main_action
      m_actions = @car_wash.actions.includes(:action_type).where("action_types.text" => "main")
      if m_actions.empty?
        @car_wash.actions << Action.create(action_text: ActionText.create(text: car_wash_params[:main_action_text]), action_type: ActionType.find_by(text: 'main'))
      else
        m_actions.first.action_text.update(text: car_wash_params[:main_action_text])
      end
      
      respond_to do |format|
        format.json { respond_with_bip(@car_wash) }
      end

  end

  # DELETE /car_washes/1
  # DELETE /car_washes/1.json
  def destroy
    @car_wash.destroy
    respond_to do |format|
      format.html { redirect_to car_washes_url }
      format.json { head :no_content }
    end
  end

  def subscribe
    @subscribe = Subscribe.new(normal_user_id: params[:user_id], car_wash_id: params[:id])

    respond_to do |format|
      if @subscribe.save
        format.html { render text: "Вы подписаны"}
        format.json { render json: @subscribe}
        format.js {}
      else
        format.json { render json: @subscribe.errors, status: :unprocessable_entity }
        format.js { alert("Ошибка") }
      end
    end
  end


  private
    def set_car_wash
      @car_wash = CarWash.find(params[:id])
    end

    def set_actions
      @actions = @car_wash.try(:actions)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_wash_params
      params.require(:car_wash).permit(
        :main_action_text, 
        :title, 
        :address, 
        :lat, 
        :lon, 
        :contacts, 
        :services, 
        :price, 
        :zones_count, 
        :video_url1, 
        :video_url2, 
        :signal,
        :site_url,
        :blink,
        :signal_changed,
        :updated_at,
        :videoned,
        :signal_type,
        actions_attributes: [:text, :action_type_text])
    end
end

app/helpers/admin/car_washes_helper.rb
module Admin::CarWashesHelper
end

app/helpers/car_washes_helper.rb
module CarWashesHelper

  def actions(actions, tag)
    ret = ""
    unless actions.empty?
      actions.each do |action|
        ret += "<#{tag}>#{action.action_text.text}</#{tag}>"
      end
    end
    raw(ret)
  end

  def car_wash_title(title)
    ret = ""
    if /\Aавтомойка/i =~ title
      ret = title
    else
      ret += "Автомойка #{title}"
    end
  end

end

app/views/admin/car_washes/_form.html.haml
= form_for [:admin, @car_wash], role: "form", html: {class: "car_wash_edit_details form-horizontal"} do |f|
  - if @car_wash.errors.any?
    #error_explanation
      %h2= "#{pluralize(@car_wash.errors.count, "error")} prohibited this car_wash from being saved:"
      %ul
        - @car_wash.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label CarWash.human_attribute_name("title"), class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label CarWash.human_attribute_name("address"), class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :address, class: 'form-control'
  .form-group
    = f.label 'Координаты', class: 'control-label col-lg-2'
    .col-lg-5
      = f.text_field :lat, class: 'form-control'
    .col-lg-5
      = f.text_field :lon, class: 'form-control'
  .form-group
    = f.label CarWash.human_attribute_name("contacts"), class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :contacts, class: 'form-control'
  .form-group
    = f.label CarWash.human_attribute_name("site_url"), class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :site_url, class: 'form-control'
  .form-group
    = f.label CarWash.human_attribute_name("video_url1"), class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :video_url1, class: 'form-control'
  .form-group
    = f.label CarWash.human_attribute_name("video_url2"), class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :video_url2, class: 'form-control'
  .form-group
    = f.label CarWash.human_attribute_name("vk_url"), class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :vk_url, class: 'form-control'
  .form-group
    = f.label CarWash.human_attribute_name("odn_url"), class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :odn_url, class: 'form-control'
  %hr
  .row
    .col-lg-1
      = f.label t("signal_type_normal"), class: 'control-label col-lg-2'
    .col-lg-2
      = f.radio_button :signal_type, 'normal', class: 'form-control', id: 'normal'
    .col-lg-1
      = f.label CarWash.human_attribute_name("blink"), class: 'control-label col-lg-2'
    .col-lg-2
      = f.radio_button :signal_type, 'blink', class: 'form-control', id: 'blink'
    .col-lg-1
      = f.label CarWash.human_attribute_name("videoned"), class: 'control-label col-lg-2'
    .col-lg-2
      = f.radio_button :signal_type, 'videoned', class: 'form-control', id: 'videoned'
    .col-lg-1
      = f.label CarWash.human_attribute_name("action_on_map"), class: 'control-label col-lg-2'
    .col-lg-2
      = f.radio_button :signal_type, 'action_on_map', class: 'form-control', id: 'action_on_map'
  %br
  %hr
  .row
    .col-lg-4.col-lg-offset-4
      = f.submit t("save_button"), class: 'btn btn-danger btn-block'

app/views/admin/car_washes/create.html.haml
%h1 Admin::CarWashes#create
%p Find me in app/views/admin/car_washes/create.html.haml

app/views/admin/car_washes/destroy.html.haml
%h1 Admin::CarWashes#destroy
%p Find me in app/views/admin/car_washes/destroy.html.haml

app/views/admin/car_washes/edit.html.haml
= render 'form'

app/views/admin/car_washes/index.html.haml
.row
  .col-lg-3
    = link_to t('new_link'), new_admin_car_wash_path, class: 'btn btn-success btn-block'

%h1= t('.header')

%table.table
  %tr
    %th N п/п
    %th= CarWash.human_attribute_name(:title)
    %th= CarWash.human_attribute_name(:address)
    %th
    %th

  - @car_washes.each_with_index do |car_wash, i|
    %tr
      %td= i+1
      %td= car_wash.title
      %td= car_wash.address
      %td= link_to t('show_link'), admin_car_wash_path(car_wash), class: 'btn btn-success'
      %td= link_to t('edit_button'), edit_admin_car_wash_path(car_wash), class: 'btn btn-danger'

app/views/admin/car_washes/new.html.haml
= render 'form'

app/views/admin/car_washes/show.html.haml
%p#notice= notice
%hr
%p
  %b= CarWash.human_attribute_name("title")
  = @car_wash.title
%p
  %b= CarWash.human_attribute_name("address")
  = @car_wash.address
%p
  %b Координаты
  = @car_wash.lat
  = @car_wash.lon
%p
  %b= CarWash.human_attribute_name("contacts")
  = @car_wash.contacts
%p
  %b= CarWash.human_attribute_name("site_url")
  = @car_wash.site_url
%p
  %b= CarWash.human_attribute_name("video_url1")
  = @car_wash.video_url1
%p
  %b= CarWash.human_attribute_name("video_url2")
  = @car_wash.video_url2
%p
  %b= CarWash.human_attribute_name("blink")
  = @car_wash.blink ? "Да":"Нет"
%p
  %b= CarWash.human_attribute_name("videoned")
  = @car_wash.videoned ? "Да":"Нет"
%p
  %b= CarWash.human_attribute_name("action_on_map")
  = @car_wash.action_on_map ? "Да":"Нет"
%p
  %b= CarWash.human_attribute_name("signal_type")
  = @car_wash.signal_type
%hr

.row
  .col-lg-2.col-lg-offset-4.actions
    = link_to t('edit_button'), edit_admin_car_wash_path(@car_wash), class: 'btn btn-danger'
  .col-lg-2.actions
    = link_to 'Назад к списку автомоек', admin_car_washes_path, class: 'btn btn-success'

app/views/admin/car_washes/update.html.haml
%h1 Admin::CarWashes#update
%p Find me in app/views/admin/car_washes/update.html.haml