config/routes.rb
Moika::Application.routes.draw do

  get "normal_users/show"
  root 'map#show'
  get "map/show"

  get "sp/:id", to: "static_pages#show", as: "static_page"
  get "banners/update"

  get "user/:id", to: "users#show", as: '/user'
  get "users/registration", to: "users#registration", as: 'registration'
  get "users/login", to: "users#login", as: 'login'

  get "normal_user/:id", to: "normal_users#show", as: '/normal_user'

  devise_for :users, controllers: { registrations: "registrations" }
  devise_for :normal_users, controllers: { registrations: "registrations" }

  resources :car_washes do
    get :update_map, on: :collection
    resources :comments, only: [:index, :create]
    resources :requests
    resources :messages, only: [:index, :show, :update]
    resources :normal_user_messages
    resources :banners, only: [:index, :update]
    resources :payments, only: [:index]
    resources :invoices, only: [:new, :create, :show]
    delete 'delete_file/:id', to: 'banners#delete_file', as: '/delete_file'
  end

  put 'car_washes/:id/update_main_action', to: 'car_washes#update_main_action', as: '/car_washes_update_main_action'
  post 'car_washes/:id/subscribe/:user_id', to: 'car_washes#subscribe', as: '/car_washes_subscribe'

  controller :robokassa do
    get "robokassa/:notification_key/notify"   => :notify,  :as => :robokassa_notification

    get "robokassa/success"  => :success, :as => :robokassa_on_success
    get "robokassa/fail"     => :fail,    :as => :robokassa_on_fail
  end

  namespace :admin do
    get '', to: 'dashboard#main', as: '/'
    get 'load_data_from_ya', to: 'dashboard#load_data_from_ya', as: '/load_data_from_ya'
    resources :users
    resources :messages, only: [:index, :show, :create, :destroy]
    resources :banners
    resources :static_pages
    resources :car_washes
    get 'add_car_wash/:id', to: 'users#add_car_wash', as: '/add_car_wash'
    delete 'delete_file/:id', to: 'banners#delete_file', as: '/delete_file'
  end
  match "*path" => redirect("/"), via: :all
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :file, BannerUploader

  default_scope {order(place: :asc)}

  def self.left
    Banner.where("place ilike 'left%'").order(:place)
  end

  def self.top
    Banner.where("place ilike 'top%'")
  end

  def self.bottom
    Banner.where("place ilike 'bottom%'")
  end

  def self.request
    Banner.where("place ilike 'request%'")
  end
  
  def self.comment
    Banner.where("place ilike 'comment%'")
  end
  
  def left?
     !(/left_/ =~ self.place).nil?
  end

  def top?
     !(/top_/ =~ self.place).nil?
  end

  def bottom?
     !(/bottom_/ =~ self.place).nil?
  end

  def left_thin_short?
    !(/left_[24]/ =~ self.place).nil?
  end

  def left_thin_long?
    !(/left_[135]/ =~ self.place).nil?
  end

  def comment?
    !(/comments_/ =~ self.place).nil?
  end

  def request?
    !(/requests_/ =~ self.place).nil?
  end

  def fat_long?
    !(/_fat_long\Z/ =~ self.place).nil?
  end

  def fat_short?
    !(/_fat_short\Z/ =~ self.place).nil?
  end

end

app/models/banners/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :file, BannerUploader

  default_scope {order(place: :asc)}

  def self.left
    Banner.where("place ilike 'left%'").order(:place)
  end

  def self.top
    Banner.where("place ilike 'top%'")
  end

  def self.bottom
    Banner.where("place ilike 'bottom%'")
  end

  def self.request
    Banner.where("place ilike 'request%'")
  end

  def self.comment
    Banner.where("place ilike 'comment%'")
  end

  def left?
     !(/left_/ =~ self.place).nil?
  end

  def top?
     !(/top_/ =~ self.place).nil?
  end

  def bottom?
     !(/bottom_/ =~ self.place).nil?
  end

  def left_thin_short?
    !(/left_[13]/ =~ self.place).nil?
  end

  def left_thin_long?
    !(/left_[2]/ =~ self.place).nil?
  end

  def comment?
    !(/comments_/ =~ self.place).nil?
  end

  def request?
    !(/requests_/ =~ self.place).nil?
  end

  def fat_long?
    !(/_fat_long\Z/ =~ self.place).nil?
  end

  def fat_short?
    !(/_fat_short\Z/ =~ self.place).nil?
  end

  def client_fat_top?
    self.place == 'client_fat_top'
  end
  def client_thin_bottom?
    self.place == 'client_thin_bottom'
  end
  def client_thin_top?
    !(/\Aclient_thin_top_/ =~ self.place).nil?
  end


end

app/models/banners/client_banner.rb
class ClientBanner < Banner
  belongs_to :car_wash, :class_name=>'CarWash', :foreign_key=>'car_wash_id'
end

app/models/banners/client_video_banner.rb
class ClientVideoBanner < ClientBanner
  before_save :change_url
  private
    def change_url
      unless self.filename.nil?
        base = "//www.youtube.com/embed/"
        suffix = "?wmode=transparent"
        query = URI.parse(self.filename).query
        if !query.nil?
          #&& (/wmode=transparent/ =~ self.filename).nil?
          self.filename = base + query[2..-1] + suffix
        else
          self.filename += suffix
        end
      end
    end
end

app/models/banners/text_banner.rb
class TextBanner < Banner
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < AdminController
  before_action :set_banner, only: [:show, :edit, :update, :destroy, :delete_file]
  skip_before_filter :verify_authenticity_token, :only => [:update]

  def index
    @banners = Banner.all
    @banners_left = Banner.left
    @banners_top = Banner.top
    @banners_bottom = Banner.bottom
    @top_text_banner = TextBanner.where(place: 'top').first
  end

  def show
  end

  def new
    @banner = Banner.new
  end

  def edit
  end

  def create
    @banner = Banner.new(banner_params)
    @banner.file = banner_params[:file]
    @banner.save!
      #render :nothing => true
      redirect_to admin_banners_path
  end

  def update
    respond_to do |format|
      if @banner.update(banner_params)
        #format.html { redirect_to [:admin, @banner], notice: 'Banner was successfully updated.' }
        logger.debug(banner_params)
        format.json
        format.js {
          render js: 'var label = $("#top_text_banner form label");
                      var prev_html = label.html();
                      console.log(prev_html);
                      label.html("Обновлено").show("slow").effect("highlight", {color: "#f77"}, 3000);
                      setTimeout(function() {label.html(prev_html);}, 3000);'
        }
      else
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to admin_banners_url }
      format.json { head :no_content }
    end
  end

  def delete_file
    @banner.remove_file!
    @banner.save!
    respond_to do |format|
      format.json { render json: @banner.to_json(only: [:id, :file]) }
    end
  end

  private
    def set_banner
      @banner = Banner.find(params[:id])
    end

    def banner_params
      params[:banner] ||= {}
      params[:banner][:file] = params[:file]
      params[:banner][:filename] = params[:name]
      params.require(:banner).permit(:file, :filename, :text, :place, :type)
    end

end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_banner, only: [:update, :destroy, :delete_file]
  skip_before_filter :verify_authenticity_token, :only => [:update]

  def index
    @car_wash = CarWash.find(params[:car_wash_id])
    @banners = @car_wash.banners
  end

  def update
    respond_to do |format|
      logger.debug "2512:vat: #{banner_params}"
      if @banner.update(banner_params)
        format.json
        format.js {}
      else
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_file
    @banner.remove_file!
    respond_to do |format|
      if @banner.save!
        format.json { render json: @banner.to_json(only: [:id, :file]) }
      else
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_banner
      @banner = Banner.find(params[:id])
    end

    def banner_params
      params[:banner] ||= {}
      logger.debug "2512:vat: #{params[:banner]}"
      params[:banner][:text] ||= params[:text]
      params[:banner][:file] ||= params[:file]
      params[:banner][:filename] ||= params[:name]
      params.require(:banner).permit(:file, :filename, :text, :place, :car_wash_id)
    end

end

app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_banner.haml
= image_tag banner_url, class: "img-thumbnail banner", 'data-toggle' => 'tooltip', 'data-id' => banner.id, id: banner.id, title: 'Кликните для редактирования'
= render '/banners/modal', banner: banner, banner_url: banner_url, version: version, car_wash: car_wash

app/views/banners/_modal.haml
.modal.fade{role: "dialog", id: "bannermodal_#{banner.id}"}
  .modal-dialog
    .modal-content
      .modal-header
        .button(type="button" class="close" data-dismiss="modal" aria-hidden="true") &times;
        .modal-title
          %h4
            Текст над баннером:
            = text_field_tag 'banner[text]', banner.text
      .modal-body
        %h4= "Размер баннера будет преобразован к: #{version[-7..-1].sub('_','x')}"
        %h4= "Максимальный размер файла: 500 kb"
        %hr
        #banner{id: banner.id, data: {url: car_wash_banner_path(car_wash, banner), token: form_authenticity_token, version: version }}
          %ul{id: "image-container_#{banner.id}", class: 'image-container'}
            %li
              %h4 Старый
              = image_tag banner_url, size: '250x150'
          %div{id: "filelist_#{banner.id}", class: 'filelist'}
      .modal-footer
        %button(type="button" class="btn btn-default" data-dismiss="modal")= t('close')
        %button(type="button" class="btn btn-danger" id="deletefiles_#{banner.id}")
          = link_to t('delete_button'), admin_delete_file_path(banner.id), data: {:confirm => t('are_you_sure')}, :method => :delete, :remote=>true, class: "delete_file"
        %button(type="button" class="btn btn-success" id="pickfiles_#{banner.id}")= t('banners.modal.choose_file')
        %button(type="submit" class="btn btn-primary" id="uploadfiles_#{banner.id}")= t('banners.modal.submit_update_image')

app/views/banners/index.html.haml
#banners{data: {ids: @banners.ids}}
#banner-top-text
  %h3.text-center.bordered Баннеры на Вашей странице:
.right-container-8
  - banner = @banners.where(type: 'ClientVideoBanner').first
  = form_for banner, url: car_wash_banner_path(@car_wash, banner), remote: true, role: 'form' do |f|
    .form-group
      = f.label :text, 'Текст над видео'
      = text_field_tag 'banner[text]', banner.text
    .form-group
      = f.label :filename, 'Путь к ролику youtube', id: "video_url_label"
      = text_field_tag 'banner[filename]', banner.filename
    = f.submit t('save_button'), class: 'btn btn-danger btn-block'

  - unless banner.blank?
    %h5.text-center.bordered= banner.text.blank? ? (raw '&nbsp;'):(banner.text)
    = render 'client_youtube', src: banner.filename
  - else
    - banner = @banners.where(place: 'client_fat_top').first
    %h5.text-center.bordered= banner.text.blank? ? (raw '&nbsp;'):(banner.text)
    = render '/banners/banner', banner: banner, banner_url: banner.file.b_770_270.url, version: :b_770_270, car_wash: @car_wash
.left-container
  - banner = @banners.where(place: 'client_thin_top_3').first
  %h5.text-center.bordered= banner.text.blank? ? (raw '&nbsp;'):(banner.text)
  = render 'banner', banner: banner, banner_url: banner.file.b_380_270.url, version: :b_380_270, car_wash: @car_wash
  
  - banner = @banners.where(place: 'client_thin_top_4').first
  %h5.text-center.bordered= banner.text.blank? ? (raw '&nbsp;'):(banner.text)
  = render 'banner', banner: banner, banner_url: banner.file.b_380_270.url, version: :b_380_270, car_wash: @car_wash
.no-edit
  .center-container
    - banner = @banners.where(place: 'client_thin_top_1').first
    %h5.text-center.bordered= banner.text.blank? ? (raw '&nbsp;'):(banner.text)

    = render 'banner', banner: banner, banner_url: banner.file.b_380_270.url, version: :b_380_270, car_wash: @car_wash
  .right-container-4
    - banner = @banners.where(place: 'client_thin_top_2').first
    %h5.text-center.bordered= banner.text.blank? ? (raw '&nbsp;'):(banner.text)
    = render 'banner', banner: banner, banner_url: banner.file.b_380_270.url, version: :b_380_270, car_wash: @car_wash

app/views/banners/update.js.erb
var label = $('#video_url_label')
label.html("Путь к ролику youtube&nbsp;Сохранено")
label.effect("highlight", {color: "#faa"}, 3000)